stages:
  - lint
  - deploy

lint-dockerfile:
  stage: lint
  image: projectatomic/dockerfile-lint
  script:
    - dockerfile_lint -p Dockerfile

# Build and deploy the CI docker image to the gitlab registry
# This is done everytime the master branch is updated
deploy-docker-image:
  image: docker:19.03.13
  tags:
  - docker
  services:
  - docker:19.03.13-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
  stage: deploy
  dependencies:
    - lint-dockerfile
  before_script:
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        export IMAGE_TAG=latest
      else
        export IMAGE_TAG=branch_${CI_COMMIT_REF_NAME}
      fi
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
